Docs contributing conduct file
ZencypherSolutions/semaphore-stellar-boilerplate pull request #5
Opened 2024-11-22 19:20 UTC by NueloSE

Closes #3

2024-11-22 20:53 UTC, evgongora commented
Hello! I think you mistaken both files.

2024-11-22 20:55 UTC, evgongora commented
Also could you follow the PR template? We use it for a reason, thank you :)

2024-11-25 08:54 UTC, NueloSE commented
@evgongora, thank you for your review. I am unclear about what you meant by "follow the PR template." I may have misunderstood the PR guide.

Here is my interpretation based on the [contribution.md](https://github.com/ZencypherSolutions/semaphore-stellar-docs/blob/main/CONTRIBUTING.md):

I created a branch named docs-contributing-conduct-file, following the contributor guide's example, For documentation: docs-meaningful-name.
Could you kindly guide me on how to improve this further? Thank you.

2024-11-25 09:01 UTC, NueloSE commented
> Hello! I think you mistaken both files.

i understand what am to do here

2024-11-25 18:32 UTC, evgongora commented
> @evgongora, thank you for your review. I am unclear about what you meant by "follow the PR template." I may have misunderstood the PR guide.
> 
> Here is my interpretation based on the [contribution.md](https://github.com/ZencypherSolutions/semaphore-stellar-docs/blob/main/CONTRIBUTING.md):
> 
> I created a branch named docs-contributing-conduct-file, following the contributor guide's example, For documentation: docs-meaningful-name. Could you kindly guide me on how to improve this further? Thank you.

Hey! @NueloSE I mean this PR template
https://github.com/ZencypherSolutions/semaphore-stellar-boilerplate/blob/main/.github/PR_TEMPLATE/PR_TEMPLATE.md

2024-11-25 18:33 UTC, evgongora commented
> > Hello! I think you mistaken both files.
> 
> i understand what am to do here

You made a switch on both docs and placed the code of conduct in the contribution.md as well as the contribution in code of conduct

2024-11-26 13:58 UTC, NueloSE commented
@evgongora thank you for your response. Implemented requested changes and ready for review

2024-11-29 05:31 UTC, evgongora commented
@NueloSE Hey! Any updates on the review?

2024-11-29 13:10 UTC, evgongora requested changes

2024-11-29 13:10 UTC, evgongora commented on CONTRIBUTING.md
> +Follow the conventional Commits specification:
Could you add here a link to the conventional commits page?

2024-11-30 20:26 UTC, NueloSE commented on CONTRIBUTING.md
> +Follow the conventional Commits specification:
okay

2024-11-30 20:34 UTC, NueloSE commented
@evgongora  requested changes have been implemented ready for review

2024-12-01 01:45 UTC, evgongora requested changes

2024-12-01 01:45 UTC, evgongora commented on CONTRIBUTING.md
> +Follow the conventional [Commits specification](https://github.com/ZencypherSolutions/semaphore-stellar-docs/blob/main/CONTRIBUTING.md#commit-your-changes)
I mean this page https://www.conventionalcommits.org/en/v1.0.0/

2024-12-01 13:53 UTC, NueloSE commented
@evgongora done

2024-12-01 19:21 UTC, evgongora approved these changes
Thank you!

2024-12-01 19:21 UTC, merged